# Generated by Django 5.0.7 on 2024-07-12 07:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='data_added',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 12, 7, 8, 1, 721763, tzinfo=datetime.timezone.utc)),
        ),
    ]
